import { test, expect } from '@playwright/test';

/**
 * Canary for the **off-CPU overlay** (OS thread context-switch profiling). Loads a fixture trace
 * that carries `ThreadContextSwitch` (kind 254) records, opens the Profiler, and asserts the
 * TimeArea filter popover exposes the "Show off-CPU intervals" toggle and that it flips state.
 *
 * The overlay itself is canvas-rendered, so there is no DOM node to assert on — the toggle is the
 * observable contract. The fixture is generated by the DEBUG-only `POST /api/fixtures/trace`
 * endpoint with `variant: 'with-context-switches'`; nothing is committed to the repo.
 */

interface SessionSummary { sessionId: string }

async function closeAllSessions(request: import('@playwright/test').APIRequestContext): Promise<void> {
  const list = await request.get('http://localhost:5173/api/sessions');
  if (!list.ok()) return;
  const { sessions = [] } = await list.json();
  for (const s of sessions as SessionSummary[]) {
    await request.delete(`http://localhost:5173/api/sessions/${s.sessionId}`, {
      headers: { 'X-Session-Token': s.sessionId },
    });
  }
}

test.describe('Profiler — off-CPU overlay (canary)', () => {
  test('context-switch trace → profiler mounts → off-CPU toggle works', async ({ page, request }) => {
    await closeAllSessions(request);

    const fx = await request.post('http://localhost:5173/api/fixtures/trace', {
      data: { variant: 'with-context-switches' },
    });
    expect(fx.ok(), 'fixture endpoint should respond 200').toBeTruthy();
    const { traceFilePath } = await fx.json();
    expect(traceFilePath, 'trace file path should be returned').toBeTruthy();

    await page.addInitScript(() => {
      try { localStorage.clear(); } catch { /* ignore */ }
    });
    await page.goto('/');

    await page.getByRole('button', { name: /^open \.typhon-trace$/i }).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await page.getByRole('tab', { name: /^open trace$/i }).click();
    await expect(page.getByRole('tab', { name: /^open trace$/i })).toHaveAttribute('data-state', 'active');
    // Paste the absolute path into the "Or paste absolute path" input — stable entry point that
    // sidesteps the FileBrowser navigation dance.
    await page.getByPlaceholder(/\.typhon-trace or/i).fill(traceFilePath);
    await page.getByRole('button', { name: /^open$/i }).click();

    await expect(page.getByRole('dialog')).not.toBeVisible({ timeout: 10_000 });
    // Profiler panel mounts — 4-tick fixture.
    await expect(page.getByText(/\b4 ticks\b/)).toBeVisible({ timeout: 15_000 });

    // Open the TimeArea filter popover and assert the off-CPU toggle is present and on by default.
    await page.getByRole('button', { name: /^filter sections$/i }).click();
    const toggle = page.getByLabel(/show off-cpu intervals/i);
    await expect(toggle).toBeVisible();
    await expect(toggle).toBeChecked();

    // Flipping it off then on must round-trip the checkbox state.
    await toggle.click();
    await expect(toggle).not.toBeChecked();
    await toggle.click();
    await expect(toggle).toBeChecked();

    await page.keyboard.press('Escape');
    await closeAllSessions(request);
  });
});
